# ==========================================
# [필수] 로컬 실행을 위한 환경변수 설정 템플릿
# 본 파일을 복사하여 'application.yml'로 이름을 변경한 뒤 값을 채워주세요.
# ==========================================

# Database
db.url=
db.username=
db.password=

# Business Key
ownerCheck.key=

# Security (JWT)
jwt.secret=

# Email Service
spring.mail.username=
spring.mail.password=

# Payment (PortOne)
portone.api-secret=

# Redis
spring.data.redis.password=

# AI (Google GenAI)
spring.ai.google.genai.api-key=