spring.config.import=optional:application-secret.properties

spring.application.name=soso
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration

server.port=80
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.expiration=1800000
jwt.refresh-expiration=604800000

# MyBatis Config
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.soso.domain.member.dto
mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.hikari.connection-init-sql=SET time_zone='+09:00'


#gcs
spring.cloud.gcp.storage.credentials.location=classpath:secure/gcs_key.json
spring.cloud.gcp.credentials.location=classpath:secure/gcs_key.json
spring.cloud.gcp.bucket=study_jcr

api.public-data.service-key=${ownerCheck.key}

spring.profiles.include=secret
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


portone.store-id=store-d07c8343-3eda-4b37-b1b1-d59c24f3d02d

portone.channel-key=channel-key-3ac881ab-bc4c-4016-b0d0-3c6eb420b83c

rag.api.url=http://localhost:8000

spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.2

# Redis
spring.data.redis.host=172.17.0.1
spring.data.redis.port=6379

